CREATE TABLE PRODUCTO(
    CODPRODUCTO NUMBER(5) NOT NULL,
    NOMBRE VARCHAR2(40) NOT NULL,
    TIPO VARCHAR2(2) NOT NULL,
    PRECIOCOSTE NUMBER(5,2) NOT NULL,
    PRECIOVENTA NUMBER(5,2) NOT NULL,
    IVA NUMBER(2) NOT NULL,
    CONSTRAINT pk_PRODUCTO PRIMARY KEY (CODPRODUCTO)
);

CREATE TABLE LINEAVENTA(
    CODPRODUCTO NUMBER(5) NOT NULL,
    CODVENTA NUMBER(5) NOT NULL,
    CANTIDAD NUMBER(2) NOT NULL,
    CONSTRAINT pk_lineaventa PRIMARY KEY(CODPRODUCTO,CODVENTA),
    CONSTRAINT fk_lineaventa FOREIGN KEY (CODVENTA) REFERENCES VENTA(CODVENTA),
    CONSTRAINT fk_linea FOREIGN KEY(CODPRODUCTO) REFERENCES PRODUCTO(CODPRODUCTO)
);

CREATE TABLE VENTA(
    CODVENTA NUMBER(5) NOT NULL,
    FECHA DATE NOT NULL,
    CONSTRAINT pk_VENTA PRIMARY KEY(CODVENTA)
);

INSERT INTO VENTA (CODVENTA, FECHA) VALUES (10000, '21/01/2023');
INSERT INTO VENTA (CODVENTA, FECHA) VALUES (10001, '20/02/2023');
INSERT INTO VENTA (CODVENTA, FECHA) VALUES (10002, '16/03/2023');
INSERT INTO VENTA (CODVENTA, FECHA) VALUES (10005, '01/01/2023');
INSERT INTO VENTA (CODVENTA, FECHA) VALUES (10010, '23/02/2023');

CREATE SEQUENCE SEQ_CODPRODUCTO START WITH 50000  INCREMENT BY 5 MAXVALUE 99999 NOCYCLE;
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'QUESO', 'L', 10.52, 25.63, 10);
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'LECHE', 'L', 10.56, 12.55, 4);
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'HUEVOS', 'H', 26.03, 35.20, 10);

INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'CARNE POLLO', 'C', 11.20, 40.90, 2);
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'CARNE TERNERA', 'C', 50.79, 64.52, 4);
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'YOGURT', 'L', 2.56, 7.55, 10);
INSERT INTO PRODUCTO(codproducto,nombre,tipo,preciocoste, precioventa, iva) VALUES (SEQ_CODPRODUCTO.NEXTVAL, 'JUDIAS', 'V', 18.90, 20.00, 4);


INSERT INTO LINEAVENTA(CODPRODUCTO, CODVENTA, CANTIDAD) VALUES (50000, 10000, 2);
INSERT INTO LINEAVENTA(CODPRODUCTO, CODVENTA, CANTIDAD) VALUES (50005, 10001, 5);
INSERT INTO LINEAVENTA(CODPRODUCTO, CODVENTA, CANTIDAD) VALUES (50010, 10002, 10);
INSERT INTO LINEAVENTA(CODPRODUCTO, CODVENTA, CANTIDAD) VALUES (50015, 10005, 11);
INSERT INTO LINEAVENTA(CODPRODUCTO, CODVENTA, CANTIDAD) VALUES (50020, 10010, 9);


--a
SELECT COUNT(*) FROM PRODUCTO WHERE PRECIOCOSTE < PRECIOVENTA/2 ;
--b
SELECT MAX (precioventa)  FROM PRODUCTO WHERE IVA =10;
--c
SELECT MIN(PRECIOVENTA) FROM PRODUCTO;
--d
SELECT COUNT(*) FROM PRODUCTO WHERE TIPO='C' AND preciocoste < precioventa/3;
--e
SELECT SUM((PRECIOVENTA*lineaventa.cantidad)-(producto.preciocoste*lineaventa.cantidad)) FROM PRODUCTO, LINEAVENTA WHERE producto.codproducto = lineaventa.codproducto AND TIPO = 'L';
--f
SELECT AVG((producto.precioventa-producto.preciocoste)*lineaventa.cantidad) FROM producto, lineaventa WHERE producto.codproducto = lineaventa.codproducto;
--g
SELECT TRUNC(PRECIOVENTA, 1),TRUNC(preciocoste, 1) FROM PRODUCTO WHERE NOMBRE LIKE UPPER('L%');
--h
SELECT ROUND(PRECIOCOSTE, 1) FROM PRODUCTO WHERE producto.precioventa >  producto.preciocoste * 1.2 AND TIPO IN('H','L');
--i
SELECT MOD(PRECIOVENTA, PRECIOCOSTE) FROM PRODUCTO WHERE IVA IN(10,4);
--j
SELECT COUNT(*) FROM venta, lineaventa WHERE venta.codventa = lineaventa.codventa;
--k
SELECT LOWER(NOMBRE) FROM PRODUCTO WHERE TIPO = 'L';








