--a
SELECT DNI FROM DEPARTAMENTO D JOIN PROFESOR USING(CODDEP) WHERE D.NOMBRE = 'INFORMATICA Y COMUNICACIONES';
--b
SELECT NOMBRE, APELLIDO FROM ALUMNO A JOIN ALUMBIL(DNI) WHERE (UPPER (LUGAR) IN ('MADRID','BARCELONA'));
--c
SELECT NOMBRE, APELLIDO FROM ALUMNO AL JOIN MATRICULA M USING(DNI) JOIN ASIGNATURA AG USING(COSASIG) WHERE UPPER(AG.NOMBRE) IN ('BASES DE DATOS', ' ACESO A DATOS');
--d
SELECT NOMBRE, APELLIDO FROM ALUMNO AL JOIN MATRICULA M USING(DNI) JOIN ASIGNATURA AG USING(CODASIG) JOIN CICLO C USING(CODCF) WHERE SIGLAS ='DAM' AND NOTA>=5;
--e
SELECT AG.NOMBRE FROM ASIGNATURA AG JOIN IMPARTE I USING(CODASIG) JOIN PROFESOR P USING(DNI) JOIN DEPARTAMENTO D USING (CODDEP) JOIN  AG