--SUBCONSULTAS--
--1
SELECT * FROM productos P WHERE id_fabricante =(SELECT f.id FROM fabricantes F WHERE F.nombre = 'Lenovo');
--2
SELECT * FROM productos P WHERE P.precio=(SELECT MAX(PRECIO) FROM productos P WHERE P.id_fabricante = (SELECT f.id FROM fabricantes F WHERE F.nombre = 'Lenovo'));
--3
SELECT nombre FROM productos WHERE PRECIO=(SELECT MAX(PRECIO) FROM productos P WHERE p.id_fabricante=(SELECT id FROM fabricantes F WHERE F.nombre = 'Lenovo') AND ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo'));
--4
SELECT NOMBRE FROM PRODUCTOS WHERE PRECIO=(SELECT MIN(PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE=(SELECT ID FROM FABRICANTES WHERE NOMBRE='Hewlett-Packard'))AND ID_FABRICANTE =(SELECT ID FROM FABRICANTES WHERE NOMBRE='Hewlett-Packard');
--5
SELECT * FROM PRODUCTOS P WHERE P.precio >=(SELECT MAX(PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE=(SELECT ID FROM FABRICANTES WHERE NOMBRE='Lenovo'));
--6
SELECT * FROM PRODUCTOS P WHERE P.PRECIO>(SELECT AVG(PRECIO) FROM PRODUCTOS WHERE ID_FABRICANTE=(SELECT ID FROM FABRICANTES WHERE NOMBRE='Asus')) AND ID_FABRICANTE = (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Asus') ;

--SUBCONSULTAS CON IN Y NOT IN--
--11 
SELECT F.NOMBRE FROM FABRICANTES F WHERE id IN(SELECT P.id_fabricante FROM productos P);
--12
SELECT F.NOMBRE FROM FABRICANTES F WHERE id NOT IN(SELECT P.id_fabricante FROM productos P);

                --APUNTES--
                -- <ANY === MENOS QUE EL MAXIMO
                SELECT p.id_fabricante FROM PRODUCTOS P WHERE ID_FABRICANTE <ANY (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo' OR NOMBRE = 'Seagate');
                
                -- >ANY === MAS QUE EL MINIMO
                SELECT p.id_fabricante FROM PRODUCTOS P WHERE ID_FABRICANTE >ANY (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo' OR NOMBRE = 'Seagate');
                
                --! =ANY === ES EQUIVALENTE A UN 'IN'¡
                SELECT * FROM PRODUCTOS P WHERE ID_FABRICANTE =ANY (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo' OR NOMBRE = 'Seagate');
                SELECT * FROM PRODUCTOS P WHERE ID_FABRICANTE IN (SELECT ID FROM FABRICANTES WHERE NOMBRE = 'Lenovo' OR NOMBRE = 'Seagate');
                
                --! <>ALL === ES EQUIVALENTE AL NOT 'IN'¡
                SELECT F.NOMBRE FROM FABRICANTES F WHERE F.ID <> ALL (SELECT ID_FABRICANTE FROM PRODUCTOS);
                SELECT F.NOMBRE FROM FABRICANTES F WHERE F.ID NOT IN(SELECT ID_FABRICANTE FROM PRODUCTOS);
                
                -- >=ALL === PRODUCTO MAS CARO
                SELECT * FROM PRODUCTOS WHERE PRECIO >= ALL (SELECT PRECIO FROM PRODUCTOS);
                
                -- <=ALL === PRODUCTO MAS BARATO
                SELECT * FROM PRODUCTOS WHERE PRECIO <= ALL (SELECT PRECIO FROM PRODUCTOS);
                
                --EXISTS 
                    --SE CUMPLE LA COMDICION
                SELECT P.NOMBRE FROM PRODUCTOS P WHERE EXISTS (SELECT ID FROM FABRICANTES WHERE NOMBRE LIKE 'H%');
                    --NO SE CUMPLE LA CONDICION
                SELECT P.NOMBRE FROM PRODUCTOS P WHERE NOT EXISTS (SELECT ID FROM FABRICANTES WHERE NOMBRE LIKE 'H%');
                
                --NOT EXISTS
                    --SE CUMPLE LA COMDICION
                SELECT P.NOMBRE FROM PRODUCTOS P WHERE NOT EXISTS (SELECT ID FROM FABRICANTES WHERE NOMBRE LIKE 'B%');
                    --NO SE CUMPLE LA COMDICION
                SELECT P.NOMBRE FROM PRODUCTOS P WHERE  EXISTS (SELECT ID FROM FABRICANTES WHERE NOMBRE LIKE 'B%');

--SUBCONSULTAS CON ANY Y ALL--
--7
SELECT * FROM PRODUCTOS WHERE PRECIO >=ALL(SELECT PRECIO FROM PRODUCTOS);
--8
SELECT * FROM PRODUCTOS WHERE PRECIO <= ALL (SELECT PRECIO FROM PRODUCTOS);
--9
SELECT NOMBRE FROM FABRICANTES F WHERE F.id =ANY(SELECT ID_FABRICANTE FROM PRODUCTOS);
--10
SELECT NOMBRE FROM FABRICANTES F WHERE F.ID <>ALL(SELECT ID_FABRICANTE FROM PRODUCTOS);


--SUBCONSULTAS EXISTS NOT EXISTS--
--13
SELECT NOMBRE FROM FABRICANTES F WHERE EXISTS(SELECT * FROM productos P WHERE P.id_fabricante = f.id);
--14
SELECT NOMBRE FROM FABRICANTES F WHERE NOT EXISTS(SELECT * FROM productos P WHERE P.id_fabricante = f.id);



