--CONSULTAS RESUMEN--
--1
SELECT * FROM PRODUCTOS P;
--2

--3
SELECT AVG(P.PRECIO) FROM PRODUCTOS P;
--4
SELECT MIN(P.PRECIO) FROM PRODUCTOS P;
--5
SELECT P.NOMBRE, p.precio FROM PRODUCTOS P WHERE P.PRECIO=(SELECT MAX(P2.PRECIO) FROM PRODUCTOS P2) ;
--6
SELECT COUNT(P.PRECIO) FROM PRODUCTOS P;