--VISTAS--
-- PASO 2 CREAMOS LA VISTA
CREATE OR REPLACE VIEW EJEMPLO AS
SELECT P.NOMBRE AS "NOMBRE_PRODUCTO",
F.NOMBRE AS "NOMBRE_FABRICANTE", PRECIO
FROM PRODUCTOS P, FABRICANTES F
WHERE p.id_fabricante = F.ID
AND PRECIO > (SELECT AVG(PRECIO) FROM PRODUCTOS);

--PARA DARNOS PERMISOS, 
GRANT CREATE VIEW TO NOMBREUSUARIO;

--PASO 3: USAR LA VISTA
SELECT * FROM EJEMPLO;
SELECT PRECIO FROM EJEMPLO;
SELECT nombre_fabricante, PRECIO FROM EJEMPLO;
 
