CREATE TABLE DIRECTOR(
    DNI VARCHAR(9),
    NOMBRE VARCHAR (30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(40),
    
    CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI)
);
CREATE TABLE SUPERMERCADO(
    CODSUP NUMBER(4),
    DIRECCION VARCHAR(50) NOT NULL,
    SUPERFICIE NUMBER(4) NOT NULL,
    -- ESALQUILER BOOLEAN,
    FECHA VARCHAR (20) NOT NULL,
    DNI_DIRECTOR VARCHAR(9) NOT NULL,
    
    CONSTRAINT PK_SUPERMERCADO PRIMARY KEY(CODSUP),
    CONSTRAINT FK_DIRECTOR_SUPERMERCADO FOREIGN KEY (DNI_DIRECTOR) REFERENCES DIRECTOR (DNI)
);

CREATE TABLE VENDEDOR(
    DNI VARCHAR(9),
    NOMBRE VARCHAR (30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(40),
    CODSUP NUMBER(4) NOT NULL, 
    
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (DNI),
    CONSTRAINT FK_VENDEDOR_SUPERMERCADO FOREIGN KEY (CODSUP) REFERENCES SUPERMERCADO (CODSUP)
);
CREATE TABLE CLIENTE(
    DNI VARCHAR(9),
    NOMBRE VARCHAR (30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DOMICILIO VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(40),
    
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE VENTA(
    CODVENTA NUMBER(4),
    FECHA DATE NOT NULL,
    DNI_VEND VARCHAR(9) NOT NULL,
    DNI_CLI VARCHAR(9) NOT NULL,
    
    CONSTRAINT PK_VENTA PRIMARY KEY(CODVENTA),
    CONSTRAINT FK_VENDEDOR_VENTA FOREIGN KEY (DNI_VEND) REFERENCES VENDEDOR(DNI),
    CONSTRAINT FK_CLIENTE_VENTA FOREIGN KEY (DNI_CLI) REFERENCES CLIENTE(DNI)
);

CREATE TABLE PRODUCTO(
    CODPRODUCTO NUMBER(4),
    DESCRIPCION VARCHAR(50) NOT NULL,
    FAMILIA VARCHAR(30) NOT NULL,
    GENERO VARCHAR (30) NOT NULL,
    DESCUENTO NUMBER(2),
    IVA NUMBER (2) NOT NULL,
    
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODPRODUCTO)
);
CREATE TABLE PRECIO(
);
ALTER TABLE SUPERMERCADO ADD ESALQUILER BOOLEAN;



